config/routes.rb
Rails.application.routes.draw do

  #Static pages
  root to: 'static_pages#city'
  get 'home', to: 'static_pages#city', as: 'home'
  get 'about', to: 'static_pages#about', as: 'about'
  get 'city', to: 'static_pages#city', as: 'city'

  #Devise
  devise_for :users
  get 'city', to: 'static_pages#city', as: :user_root

  #Spots
  resources :spots

  #comments
  resources :comments

  resources :spots do
    resources :comments, only: [:create, :destroy]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :spot
  belongs_to :user
end

app/models/spot.rb
class Spot < ApplicationRecord
  validates :address, presence: true
  belongs_to :user
  has_many :comments

  geocoded_by :address
  after_validation :geocode

  def self.search(search)
    where("title || address || description ILIKE ?", "%#{search}%")
  end

  # before_save :default_values

  private

# def default_values
#     self.completed ||= false
#     nil                       # required so that the TX will not rollback!!!
#   end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spots, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #call the configured params
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

  def create
    @spot = Spot.find(params[:spot_id])
    @comment = @spot.comments.new(params[:comment].permit(:body))
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @spot, notice: 'Comment was successfully created.'}
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @spot = Spot.find(params[:spot_id])
    @comment = @spot.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @spot, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private



  def comment_params
    params.require(:comment).permit(:body)
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spot, only: [:show, :edit, :update, :destroy, :city]

  # GET /spots
  # GET /spots.json
  def index
    @spots = current_user.spots.order(created_at: :desc)
    @hash = Gmaps4rails.build_markers(@spots) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
      marker.infowindow "<p>Spot title: #{spot.title}</p> <p>Address: #{spot.address}</p> <p>More info: #{spot.description}</p> <p>Time Limit: #{spot.time_limit}</p>"
      marker.picture({
                          "url": "http://i.imgur.com/HmtmMSt.png",
                          "width":  50,
                          "height": 50
                    })
    end
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot =Spot.find(params[:id])
    @hash = Gmaps4rails.build_markers(@spot) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
      marker.infowindow "<p>Spot title: #{spot.title}</p> <p>Address: #{spot.address}</p> <p>More info: #{spot.description}</p> <p>Time Limit: #{spot.time_limit}</p>"
      marker.picture({
                          "url": "http://i.imgur.com/HmtmMSt.png",
                          "width":  50,
                          "height": 50
                    })
    end
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
    redirect_to root_url, notice: 'Access Denied!' unless current_user.id == @spot.user.id
  end

  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)
    @spot.user = current_user        # associate the new todo to the current_user

    respond_to do |format|
      if @spot.save
        format.html { redirect_to spots_path, notice: 'Spot was successfully created.' }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1
  # PATCH/PUT /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spots_path, notice: 'Spot was successfully updated.' }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot.destroy
    respond_to do |format|
      format.html { redirect_to spots_path, notice: 'Spot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
      # redirect_to root_url, notice: 'Access Denied!' unless current_user.id == @spot.user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spot_params
      params.require(:spot).permit(:address, :time_limit, :time_limit_other, :title, :description)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

    # All spots -> city
  def city
    @spots = Spot.all
    if params[:search]
      @spots = Spot.search(params[:search]).order("created_at DESC")
    else
      @spots = Spot.all.order('created_at DESC')
    end
    @hash = Gmaps4rails.build_markers(@spots) do |spot, marker|
      marker.lat spot.latitude
      marker.lng spot.longitude
      marker.infowindow "<p>Spot title: #{spot.title}</p> <p>Address: #{spot.address}</p> <p>More info: #{spot.description}</p> <p>Time Limit: #{spot.time_limit}</p>"
      marker.picture({
                          "url": "http://i.imgur.com/HmtmMSt.png",
                          "width":  50,
                          "height": 50
                    })
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Spots"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <p>
    <strong>Posted by <%= comment.user.username %></strong></br>
    <em><%= time_ago_in_words(comment.created_at) %> ago</em></br>
    <%= comment.body %>
  </p>
  <p>
     <% if current_user.id == comment.user.id %>
      <%= button_to 'Delete', [comment.spot, comment],
                :method => :delete,
                data: { confirm: 'Are you sure?' },
                class: 'button alert'
                %>
    <% end %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :spot_id, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :spot_id, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'button' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @comment, class: 'button' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing comment</h1>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, class: 'button' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1>Listing comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Spot</th>
            <th>Body</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @comments) do |comment| %>
            <td><%= comment.spot_id %></td>
            <td><%= comment.body %></td>
            <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class="page-header">
  <%= link_to comments_path, class: 'button' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comment_path(@comment), class: 'button' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show comment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Spot:</dt>
  <dd><%= @comment.spot_id %></dd>

  <dt>Body:</dt>
  <dd><%= @comment.body %></dd>

</dl>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Foundation 6%>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="callout small-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Foundation 6 %>
<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="large">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title">FreeSpot <i class="fa fa-map-pin" aria-hidden="true"></i></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li>
        <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
  <% if signed_in? %>
    <li><%= link_to current_user.username, edit_user_registration_path %></li>
    <li><%= link_to 'My Spots', spots_path %></li>
    <li><%= link_to 'City', '/city' %></li>
    <li><%= link_to 'Sign out', destroy_user_session_path, method: 'delete' %></li>
  <% else %>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <li><%= link_to 'Sign in', new_user_session_path %></li>
  <% end %>
  <li><%= link_to 'About', '/about' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'apple-icon-57x57.png' %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'apple-icon-60x60.png' %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'apple-icon-72x72.png' %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'apple-icon-76x76.png' %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'apple-icon-114x114.png' %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'apple-icon-120x120.png' %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'apple-icon-144x144.png' %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'apple-icon-152x152.png' %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'apple-icon-180x180.png' %>">
    <link rel="icon" type="image.png' %>" sizes="192x192"  href="<%= asset_path 'android-icon-192x192.png' %>">
    <link rel="icon" type="image.png' %>" sizes="32x32" href="<%= asset_path 'favicon-32x32.png' %>">
    <link rel="icon" type="image.png' %>" sizes="96x96" href="<%= asset_path 'favicon-96x96.png' %>">
    <link rel="icon" type="image.png' %>" sizes="16x16" href="<%= asset_path 'favicon-16x16.png' %>">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="<%= asset_path 'ms-icon-144x144.png' %>">
    <meta name="theme-color" content="#ffffff">
    
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">

    <title><%= content_for?(:title) ? yield(:title) : "FreeSpot" %></title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
    <![endif]-->

    <%= stylesheet_link_tag    "application" %>

    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
<script src="//maps.google.com/maps/api/js?key=AIzaSyAd5nFl1q5g909CfNQ6y3PXy5VPJsNOxr4"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

    <%= csrf_meta_tags %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <%= yield %>

  </body>
</html>

app/views/spots/_form.html.erb
<%= form_for(@spot, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @spot.errors.any? %>
    <div class="callout alert" role="alert" data-closable>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h4>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class: "control-label" %>
    <div class="col-sm-10" id="locationField">
      <%= f.text_field :address, class: "form-control", id: "autocomplete", onFocus: "geolocate()", type: "text" %>
    </div>
  </div>

       <!-- The following code block contains information for debugging/
            testing the autocomplete form, it also contains raw code suitable
            for refactoring incase a JSON output of the autocomplete choice
            is desired later SEE: autocompleteform.js : -->

               <!-- <div id="locationField">
               <input id="autocomplete" placeholder="Enter your address" onFocus="geolocate()" type="text"></input>
               </div> -->
               <!-- Default HTML Input form field for testing -->
               <!--  <input id="autoField" name="autoField" type="text"> -->
               <!-- Full JSON Output format of selected address -->
               <!-- <div id="output"></div> -->


  <div class="form-group">
  <%= f.label :time_limit, class: "control-label" %>
    <div class="col-sm-10" id="locationField">
      <%= f.select :time_limit, options_for_select([['Unlimited'], ['30 Minutes'],['1 Hour'], ['2 Hours'], ['3 Hours'], ['4 Hours'],['Other']]) %>
      <%= f.text_field :time_limit, "data-depends-on" => "#spot_time_limit", "data-depends-on-value" => "Other" %>
    </div>
  </div>

      <div class="form-group">
    <%= f.label :description, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "button" %>
    </div>
  </div>

<% end %>

<script type="text/javascript">

      $(function() {
        var select = $('select#spot_time_limit');
        var hidden = $('input#spot_time_limit');

        hidden.hide();
        hidden.attr('disabled', true);

        select.change(function() {
          var fieldValue = select.find('option:selected').val();
          console.log(fieldValue);

        if (fieldValue === 'Other') {
            hidden.show();
            hidden.attr('disabled', false);

            populate.val("Dude");
        } else {
            hidden.hide();
            hidden.attr('disabled', true);
        }
      });
    });

</script>

    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsVKH8m8lqhOELJ347MN_m-M6-GRLlWhQ&libraries=places&callback=initAutocomplete"></script>


<%= javascript_include_tag('autocompleteform.js', defer: "defer") %>

app/views/spots/edit.html.erb
<div class="edit-spot">
  <div class="row align-left medium-unstack">
    <div class="small-12 medium-6 large-4 columns">
      <%= link_to spots_path, class: 'button' do %>
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
        Back
      <% end %>
      <%= link_to @spot, class: 'button' do %>
        <span class="glyphicon glyphicon-info-sign"></span>
        Show
      <% end %>
      <h1>Edit Your Spot</h1>

      <%= render 'form' %>
    </div>  
  </div>
</div>

app/views/spots/index.html.erb
<div class ="my-spots">
    <div class="row align-left medium-unstack">
        <div class="columns flex-video">
            <div id="map" style='max-width: 900px; height: 700px;'></div>

            <script type="text/javascript">
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
                    markers = handler.addMarkers(<%=raw @hash.to_json %>);
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                    if (markers.length === 0) {
                        markers = handler.addMarkers([
                            {
                                "lat": 33.775253,
                                "lng": -84.367066,
                                "picture": {
                                    "url": "http://i.imgur.com/W6yqCIc.png",
                                    "width":  254,
                                    "height": 96
                                },
                                "infowindow": "Welcome to FreeSpot! As you know..."
                            }
                        ]);
                        handler.bounds.extendWith(markers);
                        handler.fitMapToBounds();
                        handler.map.serviceObject.setZoom(12);
                    }
                    $(".myspots-content").on("click", "tr", function() {
                        var latitude = $(this).children(".lat").attr("class").split(' ')[0];
                        var longitude = $(this).children(".long").attr("class").split(' ')[0];
                        console.log($(this).children(".lat").attr("class").split(' ')[0]);
                        var laLatLng = new google.maps.LatLng(latitude, longitude);
                        handler.map.serviceObject.panTo(laLatLng);
                        handler.map.serviceObject.setZoom(18);
                    });

                });
            </script>
        </div>
        <div class="small-12 medium-6 large-4 columns">
          <h1>Your Spots</h1>
          <%= link_to new_spot_path, class: 'expanded button' do %>
            Add a New Spot <i class="fa fa-car" aria-hidden="true"></i>
          <% end %>
          <div class="myspots-content">
            <table class="hover">
              <tbody>
                <%= content_tag_for(:tr, @spots) do |spot| %>
                      <td><%= link_to spot.title, spot %></td>
                      <td><%= spot.address %></td>
                      <td><%= spot.time_limit %></td>
                      <!-- <td><%= spot.description %></td> -->
                      <td class="<%= spot.latitude %> lat"></td>
                      <td class="<%= spot.longitude %> long"></td>
                  <td><%= link_to spot, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button delete-button' do %>
                    <i class="fa fa-times-circle fa-2x" aria-hidden="true"></i>
                    <% end %></td>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
</div>

app/views/spots/new.html.erb
<div class="row align-left">
  <div class="new-spot medium-6 columns">
    <h1>New spot</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/spots/show.html.erb
<div class="spot-page">
  <div class="row align-left medium-unstack">
    <div class="small-11 medium-6 large-4 columns">
      <h1><%= @spot.title %></h1>
      <%= link_to spots_path, class: 'button' do %>
        <i class="fa fa-arrow-left" aria-hidden="true"></i>
        Back
      <% end %>
  <% if current_user.id == @spot.user.id %>
      <%= link_to edit_spot_path(@spot), class: 'button' do %>
        <i class="fa fa-pencil" aria-hidden="true"></i>
        Edit
      <% end %>
    <% end %>

      <dl class="dl-horizontal">
        <dt>Address:</dt>
        <dd><%= @spot.address %></dd>

        <dt>Time limit:</dt>
        <dd><%= @spot.time_limit %></dd>

        <dt>Created:</dt>
        <dd><%= @spot.created_at %></dd>
      </dl>

      <div class="spot-comments align-left">
        <h4>Comments</h4>
          <div id="comments">
            <%= render :partial => @spot.comments %>
          </div>
            <%= form_for [@spot, Comment.new] do |f| %>
              <div class="col-sm-10">
              <%= f.text_field :body, class: "form-control" %>
            </div>
              <p><%= f.submit "Add Comment", class: "button" %></p>
            <% end %>
      </div>
    </div>

      <div class="flex-video columns">
        <div id="map" style='max-width: 900px; height: 700px;'></div>

        <script type="text/javascript">
          handler = Gmaps.build('Google');
          handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers(<%=raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
          });
        </script>
      </div>
    </div>
</div>

app/views/static_pages/city.html.erb
    <% if user_signed_in? == false %>
      <div id="messageBar">
      <p>Parking can be a big deal! Help add 'Spots' and comments to the global map below to find your FreeSpot! <br><%= link_to 'Sign Up', new_user_session_path %> to join us.</p>
      </div>
    <% end %>


<div class="row align-left medium-unstack">


  <div class="columns flex-video">
      <div id="map" style='max-width: 1000px; height: 740px;'></div>

    <script type="text/javascript" defer>
      $(function() {

        handler = Gmaps.build('Google');
        handler.buildMap({ provider: { }, internal: {id: 'map'}}, function(){
          markers = handler.addMarkers(<%=raw @hash.to_json %>);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          handler.map.serviceObject.setZoom(12);
        });

        $(".spots-content").on("click", "tr", function() {
        var latitude = $(this).children(".lat").attr("class").split(' ')[0];
        var longitude = $(this).children(".long").attr("class").split(' ')[0];
        console.log($(this).children(".lat").attr("class").split(' ')[0]);
        var laLatLng = new google.maps.LatLng(latitude, longitude);
        handler.map.serviceObject.panTo(laLatLng);
        handler.map.serviceObject.setZoom(18);
        });
      });
    </script>
    </div>


  <div class ="small-12 medium-6 large-4 column">
    <% provide(:title, 'FreeSpot | City') %>

    <div class="page-header text-center">
      <h1>City Spots</h1>
    </div>
    <%= form_tag(city_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Spots" %>
      <%= submit_tag "Search", class:'button' %>
      <%= link_to "Clear", city_path, class: 'button alert' %>
    <% end %>

    <% if @spots.present? %>
      <% @spots %>
    <% else %>
      <p>There are no posts containing the term(s) <%= params[:search] %>.</p>
    <% end %>

    <div class="table spots-content">
      <table class="hover">
        <thead>
          <tr>
                <th></th>
                <th>Title</th>
                <th>Address</th>
                <th>Time limit</th>
                <th></th>
                <th></th>
          </tr>
        </thead>

        <tbody>
          <%= content_tag_for(:tr, @spots) do |spot| %>
                <td><i class="fa fa-map-pin" aria-hidden="true"></i></td>
                <td><%= link_to spot.title, spot %></td>
                <td><%= spot.address %></td>
                <td><%= spot.time_limit %></td>
                <td class="<%= spot.latitude %> lat"></td>
                <td class="<%= spot.longitude %> long"></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  </div>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="text-center jumbotron">
  <h1>Welcome to Free Spot</h1>
  <h3>This is the home page for the Rails Free Parking App with AuthN and AuthZ.</h3>
  <br/>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-primary" %>
  <%= link_to "Sign in",      new_user_session_path,      class: "btn btn-large btn-primary" %>
</div>